# enable true color support for the terminal inside tmux
set -g default-terminal "screen-256color"

# enable true color support for xterm-compatible terminals
set -ag terminal-overrides ",xterm*:Tc"

# duration that status messages remain on screen
set -g display-time 4000

# turn on mouse support
set -g mouse on

# move the status bar to the top
set-option -g status-position top
set -g status on

# start windows and panes index at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1

# ensure window index numbers get reordered on delete
set-option -g renumber-windows on

# set prefix + r keybinding to reload tmux config
unbind r
bind r source-file $XDG_CONFIG_HOME/tmux/tmux.conf

# enable vim motion in copy mode (prefix + ])
setw -g mode-keys vi

# vim motion keybindings for copy mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# open new windows and panes in current working directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# list of tpm plugins
# NOTE: press prefix + I to install the remaining plugins
set -g @plugin 'tmux-plugins/tpm'

# a set of tmux options that should be acceptable to everyone
set -g @plugin 'tmux-plugins/tmux-sensible'

# copy to the system clipboard in tmux
set -g @plugin 'tmux-plugins/tmux-yank'

# use fzf to manage your tmux work environment
set -g @plugin 'sainnhe/tmux-fzf'

# automatically adds nerd font icons support for window titles based on running programs
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'

# apply catppuccin theme for tmux
set -g @plugin 'catppuccin/tmux#v2.3.0'
set -g @catppuccin_flavor 'macchiato' # latte, frappe, macchiato or mocha

# catppuccin/tmux theme configuration options
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_directory} #{E:@catppuccin_status_session}"

set -g @catppuccin_window_left_separator "█"
set -g @catppuccin_window_right_separator ""
set -g @catppuccin_window_middle_separator " "
set -g @catppuccin_window_number_position "right"

set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W"

set -g @catppuccin_status_left_separator  ""
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_fill "icon"

set -g @catppuccin_directory_text " #{pane_current_path}"

# force transparent background on the status bar
set -g status-bg default
set -g status-style fg=default,bg=default 
set -g window-style 'fg=default,bg=default'
set -g window-active-style 'fg=default,bg=default'
set -g @catppuccin_status_background "default"

# initialize tmux plugin manager (keep this line at the very bottom of tmux.conf)
run -b '$XDG_CONFIG_HOME/tmux/plugins/tpm/tpm'
